# ==========>  README  <==========
#
# This file has been generated by:
# 
#   nix flake init --template github:zeme-iohk/iogx
#
# You should do the following:
# 
#   0. Read through this entire file once
#   1. Change the flake `description` field (line 17)
#   2. Override or add new flake inputs (line 36)
#   3. Modify the `flakeopts` value (line 41)
#   4. Run `nix develop` and read the welcome message carefully!!!
#   5. Run `cabal test all` to ensure that everything is working
#   6. Delete this comment
{
  description = "";

  inputs = {

    # The following inputs are managed by iogx:
    # 
    #   CHaP, devenv, flake-utils, haskell.nix, nixpkgs, hackage, 
    #   iohk-nix, sphinxcontrib-haddock, pre-commit-hooks-nix, 
    #   haskell-language-server, cardano-world, nosys, std, bitte-cells, tullia.
    # 
    # They will be available in both systemized and desystemized flavours. 
    # Do not re-add those inputs again here. 
    # If you need to, you can override them like this instead:
    # 
    #   iogx.inputs.hackage.url = "github:input-output-hk/hackage/my-branch" 
    iogx.url = "github:zeme-iohk/iogx";

    # Other inputs can be defined as usual.
    # foobar.url = "github:foo/bar";
  };

  outputs = inputs:
    let
      flakeopts = {

        # Boilerplate: simply pass your unmodified inputs here.
        inputs = inputs;

        # Trace debugging information.
        # This field is optional.
        # This field defaults to false.
        debug = false;

        # While migrating to IOGX, you might want to keep the old flake outputs 
        # alongside the new ones. An easy way to do this is to prefix (nest) 
        # each output group { packages, apps, devShells, <nonstandard>, ... } 
        # with a custom name.
        # This field is optional.
        # This field defaults to "", and it will have effect.
        flakeOutputsPrefix = "";

        # The root of the repository.
        # The path *must* contain the `cabal.project` file. 
        # This field is required.
        repoRoot = ./.;

        # The list of supported systems.
        # This field is optional, but it cannot be empty list.
        # This fields defaults to [ "x86_64-linux" "x86_64-darwin" ]
        systems = [ "x86_64-linux" "x86_64-darwin" ];

        # The list of supported GHC versions.
        # This field is optional, but it cannot be empty list.
        # This field defaults to [ "ghc8107" ]
        # Available compilers are: 
        #   ghc8107 ghc924
        haskellCompilers = [ "ghc8107" ];

        # The default GHC compiler.
        # When running `nix develop` this is the compiler that will be available 
        # in the shell. 
        # This field is optional, but it must be one of `haskellCompiler`.
        # It defaults to the first compiler in `haskellCompilers`.
        defaultHaskellCompiler = "ghc8107";

        # The host system for cross-compiling on migwW64.
        # Do not set this value if your project does not support 
        # cross-compilation, otherwise set this value to the host system, 
        # usually `x86_64-linux`.
        # This field is optional.
        # This field defaults to "";
        haskellCrossSystem = "";

        # A function evaluating to a haskell.nix project.
        # For documentation see the stub file ./nix/haskell-project.nix 
        # generated by the template.
        # This field is optional.
        # This field defaults to `import ./nix/haskell-project.nix`
        haskellProjectFile = import ./nix/haskell-project.nix;

        # Only for cosmetic purposes, the shell name will be included in the 
        # default `shellPrompt` and appear in the shell welcome message. 
        # You should use your project name.
        # This field is optional.
        # This field defaults to "iogx";
        shellName = "iogx";

        # Shell prompt i.e. the value of the `PS1` evnvar. 
        # This field is optional.
        # This field defaults to the familiar nix-shell green prompt.
        # NOTE: because this is a nix string that will be embedded as a bash 
        # string, you need to double-escape the left slashes:
        # Example: 
        #   bash = \n\[\033[1;32m\][nix-shell:\w]\$\[\033[0m\]
        #   shellPrompt = "\n\\[\\033[1;32m\\][nix-shell:\\w]\\$\\[\\033[0m\\] ";
        shellPrompt = "\n\\[\\033[1;32m\\][${shellName}:\\w]\\$\\[\\033[0m\\] ";

        # A function evaluating to your devShell module.
        # For documentation see the stub file ./nix/shell-module.nix 
        # generated by the template.
        # This field is optional.
        # This field defaults to `import ./nix/haskell-project.nix`
        shellModule = import ./nix/shell-module.nix;

        # Whether to run the-pre-c # TODO 
        enablePreCommitCheck = true

          includeHydraJobs ? true
          blacklistedHydraJobs ? [ ]
          excludeProfiledHaskellFromHydraJobs ? true

          includeReadTheDocsSite ? false
          readTheDocsSiteRoot ? repoRoot + "/doc"
          readTheDocsHaddockPrologue ? ""
          readTheDocsExtraHaddockPackages ? _: [ ]

          perSystemOutputs ? optionalFile (repoRoot + "/nix/per-system-outputs.nix") # TODO rename 



          # A function evaluating to a haskell.nix project.
          # For documentation see the stub file ./nix/haskell-project.nix 
          # generated by the template.
          # This is an optional field.
          haskellProjectFile = import ./nix/haskell-project.nix;

        # The host system for cross-compiling on migwW64.
        # Do not set this value if your project does not support 
        # cross-compilation, otherwise set this value to the host system, 
        # usually `x86_64-linux`.
        # This is an optional field.
        haskellCrossSystem = null;

        # Only for cosmetic purposes, the shell name will be included in the 
        # default `shellPrompt` and appear in the shell welcome message. 
        # Use should use your project name.
        shellName = "iogx";

        # A function evaluating to your devShell module.
        # For documentation see the stub file ./nix/shell-module.nix 
        # generated by the template.
        # This is an optional field.
        shellModule = import ./nix/shell-module.nix;

        # A function evaluating to system-dependent flake outputs.
        # For documentation see the stub file ./nix/per-system-outputs.nix 
        # generated by the template.
        # This is an optional field.
        perSystemOutputs = import ./nix/per-system-outputs.nix;

        # A list of derivations to be excluded from CI.
        # Each item in the list is an attribute path inside `hydraJobs` in the 
        # form of a dot-string. For example:
        #   [ "packages.my-attrs.my-nested-attr.my-pkg" "checks.exclude-me" ]
        # This defaults to the empty list.
        # blacklistedHydraJobs = [];

        # Whether to exclude profiled haskell builds from CI.
        # This defaults to true: we don't run profiled haskell builds in CI.
        # excludeProfiledHaskellFromHydraJobs = true;

        # Shell prompt i.e. the value of the `PS1` evnvar. 
        # Defaults to the legacy nix-shell green prompt using the `shellName`.
        # NOTE: because this is a nix string that will be embedded as a bash 
        # string, you need to double-escape the left slashes:
        # Example: 
        #   bash = \n\[\033[1;32m\][nix-shell:\w]\$\[\033[0m\]
        #   shellPrompt = "\n\\[\\033[1;32m\\][nix-shell:\\w]\\$\\[\\033[0m\\] ";
        # shellPrompt = "[nix-shell]";
      };
    in
    inputs.iogx.mkFlake inputs flakeopts;


  nixConfig = {

    # Do not remove these two substitures, but add to them if you wish.
    extra-substituters = [
      "https://cache.iog.io"
      "https://cache.zw3rk.com"
    ];

    # Do not remove these two public-keys, but add to them if you wish.
    extra-trusted-public-keys = [
      "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="
      "loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk="
    ];

    # Do not remove this: it's needed by haskell.nix.
    allow-import-from-derivation = true;
  };
}
