# This file is part of the IOGX [Fri Jun 16 14:54:49 2023 +0200 - a44697]
# Documentation: https://github.com/input-output-hk/iogx/blob/a44697/MANUAL.md#iogx-config
# Do not delete this autogenerated comment

{ 
  repoRoot = ./.;
  systems = [ "x86_64-linux" "x86_64-darwin" ];
  haskellCompilers = [ "ghc8107" ];
  defaultHaskellCompiler = "ghc8107";
  shouldCrossCompile = true;
}