# This file is part of the IOGX [Fri Jun 16 14:54:49 2023 +0200 - a44697]
# Documentation: https://github.com/input-output-hk/iogx/blob/a44697/MANUAL.md#per-system-outputs
# Do not delete this autogenerated comment

{ inputs, inputs', pkgs, projects }:
{
  # packages = { };
  # checks = { };
  # apps = { };
  # operables = { };
  # oci-images = { };
  # nomadTasks = { };
  # foobar = { };
}
