# This file is part of the IOGX [Fri Jun 16 14:54:49 2023 +0200 - a44697]
# Documentation: https://github.com/input-output-hk/iogx/blob/a44697/MANUAL.md#pre-commit-check
# Do not delete this autogenerated comment

# TODO rename pre-commit-hooks 

{ inputs, inputs', pkgs }:
{
  # cabal-fmt.enable = true;
  # stylish-haskell.enable = true;
  # shellcheck.enable = true;
  # prettier.enable = true;
  # editorconfig-checker.enable = true;
  # nixpkgs-fmt.enable = true;
  # png-optimization.enable = true;
  # fourmolu.enable = true;
  # hlint.enable = true;
  # hindent.enable = true;
}

